# Generated by Django 3.2.16 on 2022-11-12 21:31

import catalog.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Опишите объект. В описании обязательно должны быть слова: роскошно, или превосходно, или amazing, или wonderful', validators=[catalog.validators.validate_amazing], verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(default='', upload_to='upload/%Y/%m', verbose_name='превью'),
        ),
        migrations.DeleteModel(
            name='Preview',
        ),
    ]
