# Generated by Django 3.2.16 on 2022-11-12 21:44

import catalog.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221113_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Опишите объект. В описании обязательно должны быть слова: роскошно, или превосходно, или amazing, или wonderful', validators=[catalog.validators.validate_amazing], verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='item',
            name='upload',
            field=models.ImageField(upload_to='upload/%Y/%m', verbose_name='превью'),
        ),
    ]
