# Generated by Django 3.2.16 on 2022-11-11 21:01

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20221111_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'изображение в галерее', 'verbose_name_plural': 'изображения в галерее'},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Опишите объект', validators=[catalog.validators.validate_amazing], verbose_name='текст'),
        ),
    ]
