# Generated by Django 3.2.16 on 2022-11-11 22:08

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('img', models.ImageField(help_text='Загрузите картинку', null=True, upload_to='preview/%Y/%m', verbose_name='Изображение')),
                ('item', models.OneToOneField(help_text='Выбурите товар', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Опишите объект. В описании обязательно должны быть слова: роскошно, или превосходно, или amazing, или wonderful', validators=[catalog.validators.validate_amazing], verbose_name='текст'),
        ),
    ]
