# Generated by Django 3.2.16 on 2022-11-12 14:50

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20221112_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='Опишите объект. В описании обязательно должны быть слова: роскошно, или превосходно, или amazing, или wonderful', validators=[catalog.validators.validate_amazing], verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='item',
            field=models.OneToOneField(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.item', verbose_name='Товар'),
        ),
    ]
