# Generated by Django 3.2.16 on 2022-11-12 18:13

import catalog.validators
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20221112_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preview',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=tinymce.models.HTMLField(help_text='Опишите объект. В описании обязательно должны быть слова: роскошно, или превосходно, или amazing, или wonderful', validators=[catalog.validators.validate_amazing], verbose_name='текст'),
        ),
    ]
